wandb: Starting wandb agent 🕵️
2025-03-23 01:28:51,710 - wandb.wandb_agent - INFO - Running runs: []
2025-03-23 01:28:52,096 - wandb.wandb_agent - INFO - Agent received command: run
2025-03-23 01:28:52,098 - wandb.wandb_agent - INFO - Agent starting run with config:
	checkpoint.enabled: False
	datapipe.seed: 42
	schedule.phase1.iterations: 300
	schedule.phase1.lr_end: 1
	schedule.phase1.lr_start: 0.005
	schedule.phase2.iterations: 1500
	schedule.phase2.lr_objective: 0.001
	schedule.phase3.iterations: 2000
	schedule.phase3.lr: 0.005
	schedule.phase3.rollout_steps_increments: 5
	toggles.data.fix_data_centering: True
	toggles.data.fix_december_gap: False
	toggles.data.fix_sst_data: False
	toggles.data.fix_temporal_info: False
	toggles.data.include_sst_channel: False
	toggles.graph.use_multimesh: True
	toggles.loss.fix_inverse_variance_data: True
	toggles.loss.use_original_variable_weights: True
	toggles.model.include_solar_radiation: True
	toggles.model.include_spatial_info: True
	toggles.model.include_static_data: True
	toggles.model.include_temporal_info: False
2025-03-23 01:28:52,102 - wandb.wandb_agent - INFO - About to run command: python -m torch.distributed.run --nnodes=1 --nproc_per_node=4 train_graphcast.py checkpoint.enabled=False datapipe.seed=42 schedule.phase1.iterations=300 schedule.phase1.lr_end=1 schedule.phase1.lr_start=0.005 schedule.phase2.iterations=1500 schedule.phase2.lr_objective=0.001 schedule.phase3.iterations=2000 schedule.phase3.lr=0.005 schedule.phase3.rollout_steps_increments=5 toggles.data.fix_data_centering=True toggles.data.fix_december_gap=False toggles.data.fix_sst_data=False toggles.data.fix_temporal_info=False toggles.data.include_sst_channel=False toggles.graph.use_multimesh=True toggles.loss.fix_inverse_variance_data=True toggles.loss.use_original_variable_weights=True toggles.model.include_solar_radiation=True toggles.model.include_spatial_info=True toggles.model.include_static_data=True toggles.model.include_temporal_info=False
2025-03-23 01:28:57,106 - wandb.wandb_agent - INFO - Running runs: ['9xvz1pvd']
[2025-03-23 01:29:18,370][main][INFO] - [94mRank: 3, Device: cuda:3[0m
[2025-03-23 01:29:18,370][main][INFO] - [94mRank: 2, Device: cuda:2[0m
[2025-03-23 01:29:18,370][main][INFO] - [94mRank: 1, Device: cuda:1[0m
[2025-03-23 01:29:18,373][main][INFO] - [94mRank: 0, Device: cuda:0[0m
wandb: WARNING Unable to verify login in offline mode.
wandb: WARNING Ignoring project 'DSM500_FPR' when running a sweep.
wandb: WARNING Ignoring entity 'schups' when running a sweep.
wandb: Tracking run with wandb version 0.19.8
wandb: Run data is saved locally in /iopsstor/scratch/cscs/stefschu/DSM500_FPR/modulus-baseline/wandb/wandb/run-20250323_012919-9xvz1pvd
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run Baseline_64511_25/03/23_01:29:18_RUN_01
wandb: ⭐️ View project at https://wandb.ai/schups/DSM500_FPR
wandb: 🧹 View sweep at https://wandb.ai/schups/DSM500_FPR/sweeps/bv6kdc3l
wandb: 🚀 View run at https://wandb.ai/schups/DSM500_FPR/runs/9xvz1pvd
[2025-03-23 01:29:20,198][trainer][INFO] - [94mSetting seed to 42[0m
[2025-03-23 01:29:20,253][cache][INFO] - [94mLoading cache for 'meshes'.[0m
[2025-03-23 01:29:20,253][cache][INFO] - [94mChecking if 'meshes' is cached.[0m
[2025-03-23 01:29:20,253][cache][INFO] - [94m-> HIT! '/iopsstor/scratch/cscs/stefschu/DSM500_FPR/cache/icosahedron_meshes.pickled' exists.[0m
[2025-03-23 01:29:20,255][cache][INFO] - [94m-> Checking guard 'MeshesCacheGuard'.[0m
[2025-03-23 01:29:24,702][trainer][INFO] - [94mModel created. Trainable parameters count is 35'245'076[0m
[2025-03-23 01:29:30,437][trainer][INFO] - [92mLoaded train datapipe of size 53'947 samples[0m
/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py:912: Warning: The external source node '<modulus.datapipes.era5_hdf5.ERA5DaliExternalSource object at 0x400165ad61d0>' produces 6 outputs, but the output at the index 4 is not used. For best performance, adjust your callback so that it computes only the needed outputs.
  warnings.warn(
[2025-03-23 01:29:32,195][trainer][INFO] - [92mLoaded test datapipe of size 2'903 samples[0m
[2025-03-23 01:29:32,198][main][INFO] - [94mInitializing dataloaders...[0m
[2025-03-23 01:29:32,199][main][INFO] - [94mTraining started...[0m
/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py:912: Warning: The external source node '<modulus.datapipes.era5_hdf5.ERA5DaliExternalSource object at 0x40018ac7e980>' produces 6 outputs, but the output at the index 4 is not used. For best performance, adjust your callback so that it computes only the needed outputs.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py:912: Warning: The external source node '<modulus.datapipes.era5_hdf5.ERA5DaliExternalSource object at 0x40018ada6320>' produces 6 outputs, but the output at the index 4 is not used. For best performance, adjust your callback so that it computes only the needed outputs.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py:912: Warning: The external source node '<modulus.datapipes.era5_hdf5.ERA5DaliExternalSource object at 0x40015a5461d0>' produces 6 outputs, but the output at the index 4 is not used. For best performance, adjust your callback so that it computes only the needed outputs.
  warnings.warn(
[2025-03-23 01:30:21,284][trainer][INFO] - Iteration     1 | Train loss: 0.02 | Time taken:  8.25/40.83/49.09 sec | GPU memory: 79.1 GB | Global sample ID: 35335
[2025-03-23 01:30:22,060][trainer][INFO] - Iteration     2 | Train loss: 0.02 | Time taken:  0.00/ 0.46/ 0.46 sec | GPU memory: 82.1 GB | Global sample ID: 39950
[2025-03-23 01:30:22,475][trainer][INFO] - Iteration     3 | Train loss: 0.02 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 17002
[2025-03-23 01:30:22,866][trainer][INFO] - Iteration     4 | Train loss: 0.02 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 19918
[2025-03-23 01:30:23,263][trainer][INFO] - Iteration     5 | Train loss: 0.02 | Time taken:  0.00/ 0.28/ 0.29 sec | GPU memory: 82.1 GB | Global sample ID: 15961
[2025-03-23 01:30:23,662][trainer][INFO] - Iteration     6 | Train loss: 0.02 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 11951
[2025-03-23 01:30:24,066][trainer][INFO] - Iteration     7 | Train loss: 0.02 | Time taken:  0.00/ 0.29/ 0.29 sec | GPU memory: 82.1 GB | Global sample ID: 13377
[2025-03-23 01:30:24,517][trainer][INFO] - Iteration     8 | Train loss: 0.02 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 25632
[2025-03-23 01:30:24,907][trainer][INFO] - Iteration     9 | Train loss: 0.01 | Time taken:  0.00/ 0.28/ 0.29 sec | GPU memory: 82.1 GB | Global sample ID: 18934
[2025-03-23 01:30:25,305][trainer][INFO] - Iteration    10 | Train loss: 0.01 | Time taken:  0.00/ 0.28/ 0.29 sec | GPU memory: 82.1 GB | Global sample ID: 15906
[2025-03-23 01:30:25,801][trainer][INFO] - Iteration    11 | Train loss: 0.01 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 46823
[2025-03-23 01:30:26,191][trainer][INFO] - Iteration    12 | Train loss: 0.01 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 15819
[2025-03-23 01:30:26,631][trainer][INFO] - Iteration    13 | Train loss: 0.01 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 48235
[2025-03-23 01:30:27,038][trainer][INFO] - Iteration    14 | Train loss: 0.01 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 16177
[2025-03-23 01:30:27,431][trainer][INFO] - Iteration    15 | Train loss: 0.01 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 9930
[2025-03-23 01:30:27,827][trainer][INFO] - Iteration    16 | Train loss: 0.01 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 41644
[2025-03-23 01:30:28,226][trainer][INFO] - Iteration    17 | Train loss: 0.01 | Time taken:  0.00/ 0.29/ 0.29 sec | GPU memory: 82.1 GB | Global sample ID: 3496
[2025-03-23 01:30:28,647][trainer][INFO] - Iteration    18 | Train loss: 0.01 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 5381
[2025-03-23 01:30:29,039][trainer][INFO] - Iteration    19 | Train loss: 0.01 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 14034
[2025-03-23 01:30:29,431][trainer][INFO] - Iteration    20 | Train loss: 0.01 | Time taken:  0.00/ 0.29/ 0.29 sec | GPU memory: 82.1 GB | Global sample ID: 13919
[2025-03-23 01:30:29,822][trainer][INFO] - Iteration    21 | Train loss: 0.01 | Time taken:  0.00/ 0.28/ 0.29 sec | GPU memory: 82.1 GB | Global sample ID: 50601
[2025-03-23 01:30:30,229][trainer][INFO] - Iteration    22 | Train loss: 0.01 | Time taken:  0.00/ 0.29/ 0.29 sec | GPU memory: 82.1 GB | Global sample ID: 3080
[2025-03-23 01:30:30,735][trainer][INFO] - Iteration    23 | Train loss: 0.01 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 37483
[2025-03-23 01:30:31,125][trainer][INFO] - Iteration    24 | Train loss: 0.01 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 20487
[2025-03-23 01:30:31,516][trainer][INFO] - Iteration    25 | Train loss: 0.00 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 50335
[2025-03-23 01:30:31,988][trainer][INFO] - Iteration    26 | Train loss: 0.00 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 33107
[2025-03-23 01:30:32,378][trainer][INFO] - Iteration    27 | Train loss: 0.00 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 8050
[2025-03-23 01:30:32,806][trainer][INFO] - Iteration    28 | Train loss: 0.00 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 6767
[2025-03-23 01:30:33,196][trainer][INFO] - Iteration    29 | Train loss: 0.00 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 17381
[2025-03-23 01:30:33,605][trainer][INFO] - Iteration    30 | Train loss: 0.00 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 18720
[2025-03-23 01:30:33,993][trainer][INFO] - Iteration    31 | Train loss: 0.00 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 3462
[2025-03-23 01:30:34,400][trainer][INFO] - Iteration    32 | Train loss: 0.00 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 43268
[2025-03-23 01:30:34,792][trainer][INFO] - Iteration    33 | Train loss: 0.00 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 10175
[2025-03-23 01:30:35,189][trainer][INFO] - Iteration    34 | Train loss: 0.00 | Time taken:  0.00/ 0.28/ 0.29 sec | GPU memory: 82.1 GB | Global sample ID: 15632
[2025-03-23 01:30:35,586][trainer][INFO] - Iteration    35 | Train loss: 0.00 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 25503
[2025-03-23 01:30:35,990][trainer][INFO] - Iteration    36 | Train loss: 0.00 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 1375
[2025-03-23 01:30:36,386][trainer][INFO] - Iteration    37 | Train loss: 0.00 | Time taken:  0.00/ 0.28/ 0.29 sec | GPU memory: 82.1 GB | Global sample ID: 17910
[2025-03-23 01:30:36,779][trainer][INFO] - Iteration    38 | Train loss: 0.00 | Time taken:  0.00/ 0.28/ 0.29 sec | GPU memory: 82.1 GB | Global sample ID: 33040
[2025-03-23 01:30:37,227][trainer][INFO] - Iteration    39 | Train loss: 0.00 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 44623
[2025-03-23 01:30:37,659][trainer][INFO] - Iteration    40 | Train loss: 0.00 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 38909
[2025-03-23 01:30:38,051][trainer][INFO] - Iteration    41 | Train loss: 0.00 | Time taken:  0.00/ 0.28/ 0.29 sec | GPU memory: 82.1 GB | Global sample ID: 37918
[2025-03-23 01:30:38,517][trainer][INFO] - Iteration    42 | Train loss: 0.00 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 9131
[2025-03-23 01:30:38,955][trainer][INFO] - Iteration    43 | Train loss: 0.00 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 6797
[2025-03-23 01:30:39,345][trainer][INFO] - Iteration    44 | Train loss: 0.00 | Time taken:  0.00/ 0.28/ 0.29 sec | GPU memory: 82.1 GB | Global sample ID: 9661
[2025-03-23 01:30:39,831][trainer][INFO] - Iteration    45 | Train loss: 0.00 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 38496
[2025-03-23 01:30:40,246][trainer][INFO] - Iteration    46 | Train loss: 0.00 | Time taken:  0.00/ 0.31/ 0.31 sec | GPU memory: 82.1 GB | Global sample ID: 38616
[2025-03-23 01:30:40,695][trainer][INFO] - Iteration    47 | Train loss: 0.00 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 30779
[2025-03-23 01:30:41,088][trainer][INFO] - Iteration    48 | Train loss: 0.00 | Time taken:  0.00/ 0.29/ 0.29 sec | GPU memory: 82.1 GB | Global sample ID: 20689
[2025-03-23 01:30:41,485][trainer][INFO] - Iteration    49 | Train loss: 0.00 | Time taken:  0.00/ 0.29/ 0.29 sec | GPU memory: 82.1 GB | Global sample ID: 47508
[2025-03-23 01:30:41,897][trainer][INFO] - Iteration    50 | Train loss: 0.00 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 14450
Error executing job with overrides: ['checkpoint.enabled=False', 'datapipe.seed=42', 'schedule.phase1.iterations=300', 'schedule.phase1.lr_end=1', 'schedule.phase1.lr_start=0.005', 'schedule.phase2.iterations=1500', 'schedule.phase2.lr_objective=0.001', 'schedule.phase3.iterations=2000', 'schedule.phase3.lr=0.005', 'schedule.phase3.rollout_steps_increments=5', 'toggles.data.fix_data_centering=True', 'toggles.data.fix_december_gap=False', 'toggles.data.fix_sst_data=False', 'toggles.data.fix_temporal_info=False', 'toggles.data.include_sst_channel=False', 'toggles.graph.use_multimesh=True', 'toggles.loss.fix_inverse_variance_data=True', 'toggles.loss.use_original_variable_weights=True', 'toggles.model.include_solar_radiation=True', 'toggles.model.include_spatial_info=True', 'toggles.model.include_static_data=True', 'toggles.model.include_temporal_info=False']
Traceback (most recent call last):
  File "/iopsstor/scratch/cscs/stefschu/DSM500_FPR/modulus-baseline/train_graphcast.py", line 77, in main
    test_sample = next(iterator_testing)
  File "/iopsstor/scratch/cscs/stefschu/DSM500_FPR/modulus-baseline/modulus/datapipes/era5_hdf5.py", line 250, in __iter__
    _pipeline = dali_pth.DALIGenericIterator([self.pipe], [
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/plugin/pytorch/__init__.py", line 224, in __init__
    self._first_batch = DALIGenericIterator.__next__(self)
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/plugin/pytorch/__init__.py", line 239, in __next__
    outputs = self._get_outputs()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/plugin/base_iterator.py", line 377, in _get_outputs
    self._schedule_runs(False)
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/plugin/base_iterator.py", line 420, in _schedule_runs
    p.schedule_run()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1183, in schedule_run
    self._prefetch()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1342, in _prefetch
    self._legacy_interleaved_prefetch()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1365, in _legacy_interleaved_prefetch
    self._iter_setup()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1675, in _iter_setup
    iters, success = self._run_input_callbacks()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1724, in _run_input_callbacks
    batch.feed()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/external_source.py", line 138, in feed
    self._group.feed(self._pipepline, self._data, self._batch_size)
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/external_source.py", line 292, in feed
    pipeline._feed_input(
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1057, in _feed_input
    self._pipe.SetExternalTensorInput(
RuntimeError: Could not find an input operator with name "__ExternalSource_4"

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Error executing job with overrides: ['checkpoint.enabled=False', 'datapipe.seed=42', 'schedule.phase1.iterations=300', 'schedule.phase1.lr_end=1', 'schedule.phase1.lr_start=0.005', 'schedule.phase2.iterations=1500', 'schedule.phase2.lr_objective=0.001', 'schedule.phase3.iterations=2000', 'schedule.phase3.lr=0.005', 'schedule.phase3.rollout_steps_increments=5', 'toggles.data.fix_data_centering=True', 'toggles.data.fix_december_gap=False', 'toggles.data.fix_sst_data=False', 'toggles.data.fix_temporal_info=False', 'toggles.data.include_sst_channel=False', 'toggles.graph.use_multimesh=True', 'toggles.loss.fix_inverse_variance_data=True', 'toggles.loss.use_original_variable_weights=True', 'toggles.model.include_solar_radiation=True', 'toggles.model.include_spatial_info=True', 'toggles.model.include_static_data=True', 'toggles.model.include_temporal_info=False']
Traceback (most recent call last):
  File "/iopsstor/scratch/cscs/stefschu/DSM500_FPR/modulus-baseline/train_graphcast.py", line 77, in main
    test_sample = next(iterator_testing)
  File "/iopsstor/scratch/cscs/stefschu/DSM500_FPR/modulus-baseline/modulus/datapipes/era5_hdf5.py", line 250, in __iter__
    _pipeline = dali_pth.DALIGenericIterator([self.pipe], [
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/plugin/pytorch/__init__.py", line 224, in __init__
    self._first_batch = DALIGenericIterator.__next__(self)
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/plugin/pytorch/__init__.py", line 239, in __next__
    outputs = self._get_outputs()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/plugin/base_iterator.py", line 377, in _get_outputs
    self._schedule_runs(False)
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/plugin/base_iterator.py", line 420, in _schedule_runs
    p.schedule_run()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1183, in schedule_run
    self._prefetch()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1342, in _prefetch
    self._legacy_interleaved_prefetch()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1365, in _legacy_interleaved_prefetch
    self._iter_setup()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1675, in _iter_setup
    iters, success = self._run_input_callbacks()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1724, in _run_input_callbacks
    batch.feed()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/external_source.py", line 138, in feed
    self._group.feed(self._pipepline, self._data, self._batch_size)
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/external_source.py", line 292, in feed
    pipeline._feed_input(
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1057, in _feed_input
    self._pipe.SetExternalTensorInput(
RuntimeError: Could not find an input operator with name "__ExternalSource_4"

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Error executing job with overrides: ['checkpoint.enabled=False', 'datapipe.seed=42', 'schedule.phase1.iterations=300', 'schedule.phase1.lr_end=1', 'schedule.phase1.lr_start=0.005', 'schedule.phase2.iterations=1500', 'schedule.phase2.lr_objective=0.001', 'schedule.phase3.iterations=2000', 'schedule.phase3.lr=0.005', 'schedule.phase3.rollout_steps_increments=5', 'toggles.data.fix_data_centering=True', 'toggles.data.fix_december_gap=False', 'toggles.data.fix_sst_data=False', 'toggles.data.fix_temporal_info=False', 'toggles.data.include_sst_channel=False', 'toggles.graph.use_multimesh=True', 'toggles.loss.fix_inverse_variance_data=True', 'toggles.loss.use_original_variable_weights=True', 'toggles.model.include_solar_radiation=True', 'toggles.model.include_spatial_info=True', 'toggles.model.include_static_data=True', 'toggles.model.include_temporal_info=False']
Error executing job with overrides: ['checkpoint.enabled=False', 'datapipe.seed=42', 'schedule.phase1.iterations=300', 'schedule.phase1.lr_end=1', 'schedule.phase1.lr_start=0.005', 'schedule.phase2.iterations=1500', 'schedule.phase2.lr_objective=0.001', 'schedule.phase3.iterations=2000', 'schedule.phase3.lr=0.005', 'schedule.phase3.rollout_steps_increments=5', 'toggles.data.fix_data_centering=True', 'toggles.data.fix_december_gap=False', 'toggles.data.fix_sst_data=False', 'toggles.data.fix_temporal_info=False', 'toggles.data.include_sst_channel=False', 'toggles.graph.use_multimesh=True', 'toggles.loss.fix_inverse_variance_data=True', 'toggles.loss.use_original_variable_weights=True', 'toggles.model.include_solar_radiation=True', 'toggles.model.include_spatial_info=True', 'toggles.model.include_static_data=True', 'toggles.model.include_temporal_info=False']
Traceback (most recent call last):
  File "/iopsstor/scratch/cscs/stefschu/DSM500_FPR/modulus-baseline/train_graphcast.py", line 77, in main
    test_sample = next(iterator_testing)
  File "/iopsstor/scratch/cscs/stefschu/DSM500_FPR/modulus-baseline/modulus/datapipes/era5_hdf5.py", line 250, in __iter__
    _pipeline = dali_pth.DALIGenericIterator([self.pipe], [
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/plugin/pytorch/__init__.py", line 224, in __init__
    self._first_batch = DALIGenericIterator.__next__(self)
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/plugin/pytorch/__init__.py", line 239, in __next__
    outputs = self._get_outputs()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/plugin/base_iterator.py", line 377, in _get_outputs
    self._schedule_runs(False)
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/plugin/base_iterator.py", line 420, in _schedule_runs
    p.schedule_run()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1183, in schedule_run
    self._prefetch()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1342, in _prefetch
    self._legacy_interleaved_prefetch()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1365, in _legacy_interleaved_prefetch
    self._iter_setup()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1675, in _iter_setup
    iters, success = self._run_input_callbacks()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1724, in _run_input_callbacks
    batch.feed()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/external_source.py", line 138, in feed
    self._group.feed(self._pipepline, self._data, self._batch_size)
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/external_source.py", line 292, in feed
    pipeline._feed_input(
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1057, in _feed_input
    self._pipe.SetExternalTensorInput(
RuntimeError: Could not find an input operator with name "__ExternalSource_4"

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Traceback (most recent call last):
  File "/iopsstor/scratch/cscs/stefschu/DSM500_FPR/modulus-baseline/train_graphcast.py", line 77, in main
    test_sample = next(iterator_testing)
  File "/iopsstor/scratch/cscs/stefschu/DSM500_FPR/modulus-baseline/modulus/datapipes/era5_hdf5.py", line 250, in __iter__
    _pipeline = dali_pth.DALIGenericIterator([self.pipe], [
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/plugin/pytorch/__init__.py", line 224, in __init__
    self._first_batch = DALIGenericIterator.__next__(self)
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/plugin/pytorch/__init__.py", line 239, in __next__
    outputs = self._get_outputs()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/plugin/base_iterator.py", line 377, in _get_outputs
    self._schedule_runs(False)
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/plugin/base_iterator.py", line 420, in _schedule_runs
    p.schedule_run()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1183, in schedule_run
    self._prefetch()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1342, in _prefetch
    self._legacy_interleaved_prefetch()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1365, in _legacy_interleaved_prefetch
    self._iter_setup()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1675, in _iter_setup
    iters, success = self._run_input_callbacks()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1724, in _run_input_callbacks
    batch.feed()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/external_source.py", line 138, in feed
    self._group.feed(self._pipepline, self._data, self._batch_size)
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/external_source.py", line 292, in feed
    pipeline._feed_input(
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1057, in _feed_input
    self._pipe.SetExternalTensorInput(
RuntimeError: Could not find an input operator with name "__ExternalSource_4"

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
wandb: - 0.030 MB of 0.030 MB uploadedW0323 01:30:53.195000 41477 torch/distributed/elastic/multiprocessing/api.py:890] Sending process 41480 closing signal SIGTERM
W0323 01:30:53.203000 41477 torch/distributed/elastic/multiprocessing/api.py:890] Sending process 41481 closing signal SIGTERM
W0323 01:30:53.207000 41477 torch/distributed/elastic/multiprocessing/api.py:890] Sending process 41482 closing signal SIGTERM
/usr/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 16 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
E0323 01:30:53.988000 41477 torch/distributed/elastic/multiprocessing/api.py:862] failed (exitcode: 1) local_rank: 3 (pid: 41483) of binary: /iopsstor/scratch/cscs/stefschu/DSM500_FPR/env/venv_arm64/bin/python
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 923, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 919, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_graphcast.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-03-23_01:30:53
  host      : nid007453
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 41483)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
wandb: \ 0.030 MB of 0.051 MB uploaded2025-03-23 01:30:55,425 - wandb.wandb_agent - INFO - Cleaning up finished run: 9xvz1pvd
wandb: Terminating and syncing runs. Press ctrl-c to kill.
