wandb: Starting wandb agent 🕵️
2025-03-23 11:28:22,559 - wandb.wandb_agent - INFO - Running runs: []
2025-03-23 11:28:23,009 - wandb.wandb_agent - INFO - Agent received command: run
2025-03-23 11:28:23,010 - wandb.wandb_agent - INFO - Agent starting run with config:
	checkpoint.enabled: False
	datapipe.seed: 84
	schedule.phase1.iterations: 300
	schedule.phase1.lr_end: 1
	schedule.phase1.lr_start: 0.005
	schedule.phase2.iterations: 1500
	schedule.phase2.lr_objective: 0.001
	schedule.phase3.iterations: 2000
	schedule.phase3.lr: 0.005
	schedule.phase3.rollout_steps_increments: 5
	toggles.data.fix_data_centering: True
	toggles.data.fix_december_gap: True
	toggles.data.fix_sst_data: False
	toggles.data.fix_temporal_info: False
	toggles.data.include_sst_channel: True
	toggles.graph.use_multimesh: True
	toggles.loss.fix_inverse_variance_data: False
	toggles.loss.use_original_variable_weights: True
	toggles.model.include_solar_radiation: True
	toggles.model.include_spatial_info: True
	toggles.model.include_static_data: True
	toggles.model.include_temporal_info: False
2025-03-23 11:28:23,014 - wandb.wandb_agent - INFO - About to run command: python -m torch.distributed.run --nnodes=1 --nproc_per_node=4 train_graphcast.py checkpoint.enabled=False datapipe.seed=84 schedule.phase1.iterations=300 schedule.phase1.lr_end=1 schedule.phase1.lr_start=0.005 schedule.phase2.iterations=1500 schedule.phase2.lr_objective=0.001 schedule.phase3.iterations=2000 schedule.phase3.lr=0.005 schedule.phase3.rollout_steps_increments=5 toggles.data.fix_data_centering=True toggles.data.fix_december_gap=True toggles.data.fix_sst_data=False toggles.data.fix_temporal_info=False toggles.data.include_sst_channel=True toggles.graph.use_multimesh=True toggles.loss.fix_inverse_variance_data=False toggles.loss.use_original_variable_weights=True toggles.model.include_solar_radiation=True toggles.model.include_spatial_info=True toggles.model.include_static_data=True toggles.model.include_temporal_info=False
2025-03-23 11:28:28,023 - wandb.wandb_agent - INFO - Running runs: ['n9p6wecc']
[2025-03-23 11:28:48,737][main][INFO] - [94mRank: 3, Device: cuda:3[0m
[2025-03-23 11:28:48,737][main][INFO] - [94mRank: 1, Device: cuda:1[0m
[2025-03-23 11:28:48,737][main][INFO] - [94mRank: 2, Device: cuda:2[0m
[2025-03-23 11:28:48,742][main][INFO] - [94mRank: 0, Device: cuda:0[0m
wandb: WARNING Unable to verify login in offline mode.
wandb: WARNING Ignoring project 'DSM500_FPR' when running a sweep.
wandb: WARNING Ignoring entity 'schups' when running a sweep.
wandb: Tracking run with wandb version 0.19.8
wandb: Run data is saved locally in /iopsstor/scratch/cscs/stefschu/DSM500_FPR/modulus-baseline/wandb/wandb/run-20250323_112849-n9p6wecc
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run Baseline_64748_25/03/23_11:28:48_RUN_01
wandb: ⭐️ View project at https://wandb.ai/schups/DSM500_FPR
wandb: 🧹 View sweep at https://wandb.ai/schups/DSM500_FPR/sweeps/bv6kdc3l
wandb: 🚀 View run at https://wandb.ai/schups/DSM500_FPR/runs/n9p6wecc
[2025-03-23 11:28:50,524][trainer][INFO] - [94mSetting seed to 84[0m
[2025-03-23 11:28:50,580][cache][INFO] - [94mLoading cache for 'meshes'.[0m
[2025-03-23 11:28:50,580][cache][INFO] - [94mChecking if 'meshes' is cached.[0m
[2025-03-23 11:28:50,580][cache][INFO] - [94m-> HIT! '/iopsstor/scratch/cscs/stefschu/DSM500_FPR/cache/icosahedron_meshes.pickled' exists.[0m
[2025-03-23 11:28:50,582][cache][INFO] - [94m-> Checking guard 'MeshesCacheGuard'.[0m
[2025-03-23 11:28:55,021][trainer][INFO] - [94mModel created. Trainable parameters count is 35'246'101[0m
[2025-03-23 11:29:00,686][trainer][INFO] - [92mLoaded train datapipe of size 54'019 samples[0m
/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py:912: Warning: The external source node '<modulus.datapipes.era5_hdf5.ERA5DaliExternalSource object at 0x40018bef5ed0>' produces 6 outputs, but the output at the index 4 is not used. For best performance, adjust your callback so that it computes only the needed outputs.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py:912: Warning: The external source node '<modulus.datapipes.era5_hdf5.ERA5DaliExternalSource object at 0x40015cd76290>' produces 6 outputs, but the output at the index 4 is not used. For best performance, adjust your callback so that it computes only the needed outputs.
  warnings.warn(
[2025-03-23 11:29:02,457][trainer][INFO] - [92mLoaded test datapipe of size 2'912 samples[0m
[2025-03-23 11:29:02,460][main][INFO] - [94mInitializing dataloaders...[0m
[2025-03-23 11:29:02,461][main][INFO] - [94mTraining started...[0m
/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py:912: Warning: The external source node '<modulus.datapipes.era5_hdf5.ERA5DaliExternalSource object at 0x40017fcd31c0>' produces 6 outputs, but the output at the index 4 is not used. For best performance, adjust your callback so that it computes only the needed outputs.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py:912: Warning: The external source node '<modulus.datapipes.era5_hdf5.ERA5DaliExternalSource object at 0x400170e25ff0>' produces 6 outputs, but the output at the index 4 is not used. For best performance, adjust your callback so that it computes only the needed outputs.
  warnings.warn(
[2025-03-23 11:29:57,150][trainer][INFO] - Iteration     1 | Train loss: 4.85 | Time taken:  8.24/46.45/54.69 sec | GPU memory: 79.1 GB | Global sample ID: 45860
[2025-03-23 11:29:57,732][trainer][INFO] - Iteration     2 | Train loss: 4.68 | Time taken:  0.00/ 0.27/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 53059
[2025-03-23 11:29:58,121][trainer][INFO] - Iteration     3 | Train loss: 4.35 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 30203
[2025-03-23 11:29:58,646][trainer][INFO] - Iteration     4 | Train loss: 4.43 | Time taken:  0.00/ 0.27/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 21180
[2025-03-23 11:29:59,035][trainer][INFO] - Iteration     5 | Train loss: 3.97 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 35723
[2025-03-23 11:29:59,433][trainer][INFO] - Iteration     6 | Train loss: 3.38 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 27154
[2025-03-23 11:29:59,834][trainer][INFO] - Iteration     7 | Train loss: 3.08 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 15476
[2025-03-23 11:30:00,234][trainer][INFO] - Iteration     8 | Train loss: 2.49 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 8090
[2025-03-23 11:30:00,631][trainer][INFO] - Iteration     9 | Train loss: 2.21 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 43331
[2025-03-23 11:30:01,030][trainer][INFO] - Iteration    10 | Train loss: 1.74 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 2874
[2025-03-23 11:30:01,695][trainer][INFO] - Iteration    11 | Train loss: 1.20 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 2008
[2025-03-23 11:30:02,083][trainer][INFO] - Iteration    12 | Train loss: 0.84 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 11928
[2025-03-23 11:30:02,481][trainer][INFO] - Iteration    13 | Train loss: 0.63 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 30827
[2025-03-23 11:30:02,880][trainer][INFO] - Iteration    14 | Train loss: 0.50 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 52149
[2025-03-23 11:30:03,277][trainer][INFO] - Iteration    15 | Train loss: 0.41 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 14990
[2025-03-23 11:30:03,676][trainer][INFO] - Iteration    16 | Train loss: 0.46 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 26934
[2025-03-23 11:30:04,075][trainer][INFO] - Iteration    17 | Train loss: 0.34 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 17494
[2025-03-23 11:30:04,476][trainer][INFO] - Iteration    18 | Train loss: 0.31 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 12478
[2025-03-23 11:30:04,876][trainer][INFO] - Iteration    19 | Train loss: 0.23 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 50172
[2025-03-23 11:30:05,278][trainer][INFO] - Iteration    20 | Train loss: 0.23 | Time taken:  0.00/ 0.29/ 0.29 sec | GPU memory: 82.1 GB | Global sample ID: 46336
[2025-03-23 11:30:05,677][trainer][INFO] - Iteration    21 | Train loss: 0.26 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 41035
[2025-03-23 11:30:06,076][trainer][INFO] - Iteration    22 | Train loss: 0.24 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 1700
[2025-03-23 11:30:06,475][trainer][INFO] - Iteration    23 | Train loss: 0.19 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 38511
[2025-03-23 11:30:06,875][trainer][INFO] - Iteration    24 | Train loss: 0.18 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 10588
[2025-03-23 11:30:07,277][trainer][INFO] - Iteration    25 | Train loss: 0.19 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 27369
[2025-03-23 11:30:07,675][trainer][INFO] - Iteration    26 | Train loss: 0.19 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 33913
[2025-03-23 11:30:08,316][trainer][INFO] - Iteration    27 | Train loss: 0.18 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 34700
[2025-03-23 11:30:08,707][trainer][INFO] - Iteration    28 | Train loss: 0.18 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 14638
[2025-03-23 11:30:09,109][trainer][INFO] - Iteration    29 | Train loss: 0.18 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 7967
[2025-03-23 11:30:09,511][trainer][INFO] - Iteration    30 | Train loss: 0.16 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 20441
[2025-03-23 11:30:09,914][trainer][INFO] - Iteration    31 | Train loss: 0.15 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 39676
[2025-03-23 11:30:10,315][trainer][INFO] - Iteration    32 | Train loss: 0.14 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 53428
[2025-03-23 11:30:10,939][trainer][INFO] - Iteration    33 | Train loss: 0.15 | Time taken:  0.00/ 0.30/ 0.30 sec | GPU memory: 82.1 GB | Global sample ID: 7604
[2025-03-23 11:30:11,337][trainer][INFO] - Iteration    34 | Train loss: 0.13 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 50111
[2025-03-23 11:30:11,741][trainer][INFO] - Iteration    35 | Train loss: 0.13 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 51471
[2025-03-23 11:30:12,141][trainer][INFO] - Iteration    36 | Train loss: 0.13 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 2022
[2025-03-23 11:30:12,541][trainer][INFO] - Iteration    37 | Train loss: 0.15 | Time taken:  0.00/ 0.28/ 0.29 sec | GPU memory: 82.1 GB | Global sample ID: 24320
[2025-03-23 11:30:12,942][trainer][INFO] - Iteration    38 | Train loss: 0.11 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 19922
[2025-03-23 11:30:13,340][trainer][INFO] - Iteration    39 | Train loss: 0.12 | Time taken:  0.00/ 0.28/ 0.29 sec | GPU memory: 82.1 GB | Global sample ID: 28337
[2025-03-23 11:30:13,739][trainer][INFO] - Iteration    40 | Train loss: 0.12 | Time taken:  0.00/ 0.28/ 0.29 sec | GPU memory: 82.1 GB | Global sample ID: 47445
[2025-03-23 11:30:14,141][trainer][INFO] - Iteration    41 | Train loss: 0.12 | Time taken:  0.00/ 0.28/ 0.29 sec | GPU memory: 82.1 GB | Global sample ID: 91
[2025-03-23 11:30:14,541][trainer][INFO] - Iteration    42 | Train loss: 0.12 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 32247
[2025-03-23 11:30:14,940][trainer][INFO] - Iteration    43 | Train loss: 0.11 | Time taken:  0.00/ 0.28/ 0.29 sec | GPU memory: 82.1 GB | Global sample ID: 25422
[2025-03-23 11:30:15,568][trainer][INFO] - Iteration    44 | Train loss: 0.13 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 23517
[2025-03-23 11:30:15,960][trainer][INFO] - Iteration    45 | Train loss: 0.09 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 21312
[2025-03-23 11:30:16,359][trainer][INFO] - Iteration    46 | Train loss: 0.11 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 26228
[2025-03-23 11:30:16,760][trainer][INFO] - Iteration    47 | Train loss: 0.11 | Time taken:  0.00/ 0.28/ 0.29 sec | GPU memory: 82.1 GB | Global sample ID: 44508
[2025-03-23 11:30:17,159][trainer][INFO] - Iteration    48 | Train loss: 0.09 | Time taken:  0.00/ 0.28/ 0.29 sec | GPU memory: 82.1 GB | Global sample ID: 40684
[2025-03-23 11:30:17,561][trainer][INFO] - Iteration    49 | Train loss: 0.09 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 2416
[2025-03-23 11:30:17,958][trainer][INFO] - Iteration    50 | Train loss: 0.10 | Time taken:  0.00/ 0.28/ 0.29 sec | GPU memory: 82.1 GB | Global sample ID: 34267
Error executing job with overrides: ['checkpoint.enabled=False', 'datapipe.seed=84', 'schedule.phase1.iterations=300', 'schedule.phase1.lr_end=1', 'schedule.phase1.lr_start=0.005', 'schedule.phase2.iterations=1500', 'schedule.phase2.lr_objective=0.001', 'schedule.phase3.iterations=2000', 'schedule.phase3.lr=0.005', 'schedule.phase3.rollout_steps_increments=5', 'toggles.data.fix_data_centering=True', 'toggles.data.fix_december_gap=True', 'toggles.data.fix_sst_data=False', 'toggles.data.fix_temporal_info=False', 'toggles.data.include_sst_channel=True', 'toggles.graph.use_multimesh=True', 'toggles.loss.fix_inverse_variance_data=False', 'toggles.loss.use_original_variable_weights=True', 'toggles.model.include_solar_radiation=True', 'toggles.model.include_spatial_info=True', 'toggles.model.include_static_data=True', 'toggles.model.include_temporal_info=False']
Traceback (most recent call last):
  File "/iopsstor/scratch/cscs/stefschu/DSM500_FPR/modulus-baseline/train_graphcast.py", line 77, in main
    test_sample = next(iterator_testing)
  File "/iopsstor/scratch/cscs/stefschu/DSM500_FPR/modulus-baseline/modulus/datapipes/era5_hdf5.py", line 250, in __iter__
    _pipeline = dali_pth.DALIGenericIterator([self.pipe], [
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/plugin/pytorch/__init__.py", line 224, in __init__
    self._first_batch = DALIGenericIterator.__next__(self)
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/plugin/pytorch/__init__.py", line 239, in __next__
    outputs = self._get_outputs()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/plugin/base_iterator.py", line 377, in _get_outputs
    self._schedule_runs(False)
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/plugin/base_iterator.py", line 420, in _schedule_runs
    p.schedule_run()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1183, in schedule_run
    self._prefetch()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1342, in _prefetch
    self._legacy_interleaved_prefetch()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1365, in _legacy_interleaved_prefetch
    self._iter_setup()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1675, in _iter_setup
    iters, success = self._run_input_callbacks()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1724, in _run_input_callbacks
    batch.feed()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/external_source.py", line 138, in feed
    self._group.feed(self._pipepline, self._data, self._batch_size)
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/external_source.py", line 292, in feed
    pipeline._feed_input(
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1057, in _feed_input
    self._pipe.SetExternalTensorInput(
RuntimeError: Could not find an input operator with name "__ExternalSource_4"

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Error executing job with overrides: ['checkpoint.enabled=False', 'datapipe.seed=84', 'schedule.phase1.iterations=300', 'schedule.phase1.lr_end=1', 'schedule.phase1.lr_start=0.005', 'schedule.phase2.iterations=1500', 'schedule.phase2.lr_objective=0.001', 'schedule.phase3.iterations=2000', 'schedule.phase3.lr=0.005', 'schedule.phase3.rollout_steps_increments=5', 'toggles.data.fix_data_centering=True', 'toggles.data.fix_december_gap=True', 'toggles.data.fix_sst_data=False', 'toggles.data.fix_temporal_info=False', 'toggles.data.include_sst_channel=True', 'toggles.graph.use_multimesh=True', 'toggles.loss.fix_inverse_variance_data=False', 'toggles.loss.use_original_variable_weights=True', 'toggles.model.include_solar_radiation=True', 'toggles.model.include_spatial_info=True', 'toggles.model.include_static_data=True', 'toggles.model.include_temporal_info=False']
Traceback (most recent call last):
  File "/iopsstor/scratch/cscs/stefschu/DSM500_FPR/modulus-baseline/train_graphcast.py", line 77, in main
    test_sample = next(iterator_testing)
  File "/iopsstor/scratch/cscs/stefschu/DSM500_FPR/modulus-baseline/modulus/datapipes/era5_hdf5.py", line 250, in __iter__
    _pipeline = dali_pth.DALIGenericIterator([self.pipe], [
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/plugin/pytorch/__init__.py", line 224, in __init__
    self._first_batch = DALIGenericIterator.__next__(self)
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/plugin/pytorch/__init__.py", line 239, in __next__
    outputs = self._get_outputs()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/plugin/base_iterator.py", line 377, in _get_outputs
    self._schedule_runs(False)
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/plugin/base_iterator.py", line 420, in _schedule_runs
    p.schedule_run()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1183, in schedule_run
    self._prefetch()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1342, in _prefetch
    self._legacy_interleaved_prefetch()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1365, in _legacy_interleaved_prefetch
    self._iter_setup()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1675, in _iter_setup
    iters, success = self._run_input_callbacks()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1724, in _run_input_callbacks
    batch.feed()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/external_source.py", line 138, in feed
    self._group.feed(self._pipepline, self._data, self._batch_size)
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/external_source.py", line 292, in feed
    pipeline._feed_input(
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1057, in _feed_input
    self._pipe.SetExternalTensorInput(
RuntimeError: Could not find an input operator with name "__ExternalSource_4"

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Error executing job with overrides: ['checkpoint.enabled=False', 'datapipe.seed=84', 'schedule.phase1.iterations=300', 'schedule.phase1.lr_end=1', 'schedule.phase1.lr_start=0.005', 'schedule.phase2.iterations=1500', 'schedule.phase2.lr_objective=0.001', 'schedule.phase3.iterations=2000', 'schedule.phase3.lr=0.005', 'schedule.phase3.rollout_steps_increments=5', 'toggles.data.fix_data_centering=True', 'toggles.data.fix_december_gap=True', 'toggles.data.fix_sst_data=False', 'toggles.data.fix_temporal_info=False', 'toggles.data.include_sst_channel=True', 'toggles.graph.use_multimesh=True', 'toggles.loss.fix_inverse_variance_data=False', 'toggles.loss.use_original_variable_weights=True', 'toggles.model.include_solar_radiation=True', 'toggles.model.include_spatial_info=True', 'toggles.model.include_static_data=True', 'toggles.model.include_temporal_info=False']
Traceback (most recent call last):
  File "/iopsstor/scratch/cscs/stefschu/DSM500_FPR/modulus-baseline/train_graphcast.py", line 77, in main
    test_sample = next(iterator_testing)
  File "/iopsstor/scratch/cscs/stefschu/DSM500_FPR/modulus-baseline/modulus/datapipes/era5_hdf5.py", line 250, in __iter__
    _pipeline = dali_pth.DALIGenericIterator([self.pipe], [
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/plugin/pytorch/__init__.py", line 224, in __init__
    self._first_batch = DALIGenericIterator.__next__(self)
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/plugin/pytorch/__init__.py", line 239, in __next__
    outputs = self._get_outputs()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/plugin/base_iterator.py", line 377, in _get_outputs
    self._schedule_runs(False)
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/plugin/base_iterator.py", line 420, in _schedule_runs
    p.schedule_run()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1183, in schedule_run
    self._prefetch()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1342, in _prefetch
    self._legacy_interleaved_prefetch()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1365, in _legacy_interleaved_prefetch
    self._iter_setup()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1675, in _iter_setup
    iters, success = self._run_input_callbacks()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1724, in _run_input_callbacks
    batch.feed()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/external_source.py", line 138, in feed
    self._group.feed(self._pipepline, self._data, self._batch_size)
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/external_source.py", line 292, in feed
    pipeline._feed_input(
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1057, in _feed_input
    self._pipe.SetExternalTensorInput(
RuntimeError: Could not find an input operator with name "__ExternalSource_4"

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Error executing job with overrides: ['checkpoint.enabled=False', 'datapipe.seed=84', 'schedule.phase1.iterations=300', 'schedule.phase1.lr_end=1', 'schedule.phase1.lr_start=0.005', 'schedule.phase2.iterations=1500', 'schedule.phase2.lr_objective=0.001', 'schedule.phase3.iterations=2000', 'schedule.phase3.lr=0.005', 'schedule.phase3.rollout_steps_increments=5', 'toggles.data.fix_data_centering=True', 'toggles.data.fix_december_gap=True', 'toggles.data.fix_sst_data=False', 'toggles.data.fix_temporal_info=False', 'toggles.data.include_sst_channel=True', 'toggles.graph.use_multimesh=True', 'toggles.loss.fix_inverse_variance_data=False', 'toggles.loss.use_original_variable_weights=True', 'toggles.model.include_solar_radiation=True', 'toggles.model.include_spatial_info=True', 'toggles.model.include_static_data=True', 'toggles.model.include_temporal_info=False']
Traceback (most recent call last):
  File "/iopsstor/scratch/cscs/stefschu/DSM500_FPR/modulus-baseline/train_graphcast.py", line 77, in main
    test_sample = next(iterator_testing)
  File "/iopsstor/scratch/cscs/stefschu/DSM500_FPR/modulus-baseline/modulus/datapipes/era5_hdf5.py", line 250, in __iter__
    _pipeline = dali_pth.DALIGenericIterator([self.pipe], [
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/plugin/pytorch/__init__.py", line 224, in __init__
    self._first_batch = DALIGenericIterator.__next__(self)
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/plugin/pytorch/__init__.py", line 239, in __next__
    outputs = self._get_outputs()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/plugin/base_iterator.py", line 377, in _get_outputs
    self._schedule_runs(False)
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/plugin/base_iterator.py", line 420, in _schedule_runs
    p.schedule_run()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1183, in schedule_run
    self._prefetch()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1342, in _prefetch
    self._legacy_interleaved_prefetch()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1365, in _legacy_interleaved_prefetch
    self._iter_setup()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1675, in _iter_setup
    iters, success = self._run_input_callbacks()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1724, in _run_input_callbacks
    batch.feed()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/external_source.py", line 138, in feed
    self._group.feed(self._pipepline, self._data, self._batch_size)
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/external_source.py", line 292, in feed
    pipeline._feed_input(
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1057, in _feed_input
    self._pipe.SetExternalTensorInput(
RuntimeError: Could not find an input operator with name "__ExternalSource_4"

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
W0323 11:30:28.923000 291358 torch/distributed/elastic/multiprocessing/api.py:890] Sending process 291362 closing signal SIGTERM
W0323 11:30:28.925000 291358 torch/distributed/elastic/multiprocessing/api.py:890] Sending process 291364 closing signal SIGTERM
W0323 11:30:28.927000 291358 torch/distributed/elastic/multiprocessing/api.py:890] Sending process 291365 closing signal SIGTERM
/usr/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 16 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
wandb: - 0.030 MB of 0.030 MB uploadedE0323 11:30:29.596000 291358 torch/distributed/elastic/multiprocessing/api.py:862] failed (exitcode: 1) local_rank: 1 (pid: 291363) of binary: /iopsstor/scratch/cscs/stefschu/DSM500_FPR/env/venv_arm64/bin/python
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 923, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 919, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_graphcast.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-03-23_11:30:28
  host      : nid005913
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 291363)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
2025-03-23 11:30:31,482 - wandb.wandb_agent - INFO - Cleaning up finished run: n9p6wecc
wandb: Terminating and syncing runs. Press ctrl-c to kill.
